// apps/dashboard-react/src/bootstrap.tsx
import type { MfeMountContext, MfeUnmount } from '@banking/contracts';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

import { App } from './App';
import { ApiError } from './services/api-client';
import { ShellProvider } from './shell/shell-context';

/**
 * Starts the React application inside an element the caller owns.
 *
 * Kept separate from `mount.tsx` on purpose. `mount.tsx` is the module Module
 * Federation virtualises, and letting the standalone entry import from it too
 * gives the bundler two routes into the same module — a race that surfaces as
 * an intermittent "mount is not exported" at build time. Both entry points
 * depend on *this* module instead, and the federation boundary stays a boundary.
 */
export function bootstrapDashboard(
  element: HTMLElement,
  context: MfeMountContext,
): MfeUnmount {
  const queryClient = createQueryClient();
  const root = createRoot(element);

  root.render(
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <ShellProvider context={context}>
          <App />
        </ShellProvider>
      </QueryClientProvider>
    </StrictMode>,
  );

  return () => {
    root.unmount();
    // The cache is per-mount. Leaving it behind would let a second user, after
    // a logout and login in the same tab, briefly see the first one's balances.
    queryClient.clear();
  };
}

function createQueryClient(): QueryClient {
  return new QueryClient({
    defaultOptions: {
      queries: {
        // Retrying a 401 or a 403 cannot succeed and only delays the error the
        // user needs to see; a 5xx or a dropped connection is worth two tries.
        retry: (failureCount, error) => {
          if (error instanceof ApiError && error.statusCode < 500) return false;
          return failureCount < 2;
        },
        refetchOnWindowFocus: false,
      },
    },
  });
}

// apps/transfer-angular/src/bootstrap.ts
import type { MfeMountContext, MfeUnmount } from '@banking/contracts';
import { LocationStrategy } from '@angular/common';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { type ApplicationRef, provideZonelessChangeDetection } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';

import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';
import { ShellLocationStrategy } from './app/core/shell-location.strategy';
import { SHELL_CONTEXT } from './app/core/shell-context.token';
import { authInterceptor } from './app/interceptors/auth.interceptor';

/**
 * Starts the Angular application inside an element the caller owns.
 *
 * Kept separate from `mount.ts` on purpose. `mount.ts` is the module Module
 * Federation virtualises, and having the standalone entry import from it too
 * gives the bundler two routes into the same module — a race that shows up as
 * an intermittent `"mount" is not exported by "src/mount.ts"` at build time.
 * Both entry points depend on *this* module instead, and the federation
 * boundary stays a boundary.
 */
export async function bootstrapTransfer(
  element: HTMLElement,
  context: MfeMountContext,
): Promise<MfeUnmount> {
  // Angular bootstraps into a component's selector, so the host element has to
  // carry it. Creating a child leaves the caller's element untouched.
  const host = document.createElement('bank-transfer-root');
  element.appendChild(host);

  const app: ApplicationRef = await bootstrapApplication(AppComponent, {
    providers: [
      { provide: SHELL_CONTEXT, useValue: context },
      // Zoneless: zone.js monkey-patches setTimeout, Promise and every DOM
      // event globally. In a page it shares with React and Vue, that is not a
      // local decision — it changes how *their* async code behaves too.
      provideZonelessChangeDetection(),
      provideHttpClient(withInterceptors([authInterceptor])),
      provideRouter(routes),
      // Replaces Angular's own history handling; see ShellLocationStrategy.
      { provide: LocationStrategy, useClass: ShellLocationStrategy },
    ],
  });

  return () => {
    app.destroy();
    host.remove();
  };
}
